### ISSUE TITLE
图片压缩报错

### ISSUE THREAD

**Issue by j512581813** [onface/gulp-book#38]
我运行你的代码出现下面的错误 请问这个是什么原因
![qq 20170111142255](https://cloud.githubusercontent.com/assets/15359057/21837818/84c1192c-d809-11e6-8c2c-761f1e0d488c.png)

**Comment by johanazhu** [comment]
我也一样，找不到原因啊

**Comment by johanazhu** [comment]
大兄弟，我找到我的问题的原因了。报错和你一样，我用的是淘宝镜像，下载后的代码不对，所有出错了。改用npm install gulp-imagemin -D 就能压缩图片了
