### ISSUE TITLE
 vfs.watch is not a function

### ISSUE THREAD

**Issue by Mirror198829** [onface/gulp-book#40]
gulp watch 执行后，显示 vfs.watch is not a funciton,如何解决？

**Comment by xiaoniudadi** [comment]
你看一下你在执行的之前有没有把所有的插件引入进来，最好是把当前的gulp.js文件中所有用到的在重新引入一遍，这里有一个stackoverflow的解决方法，你可以参考一下
https://stackoverflow.com/questions/33266398/gulp-error-vfs-watch-is-not-a-function

**Comment by Mirror198829** [comment]
好的  谢啦
