### ISSUE TITLE
命令行运行gulp的时候出错

### ISSUE THREAD

**Issue by ZhaoYLi** [onface/gulp-book#43]
目录结构：
![image](https://user-images.githubusercontent.com/28992657/36089483-22ef6de2-1017-11e8-8a13-41e79dcdc3ab.png)

package.json文件
![image](https://user-images.githubusercontent.com/28992657/36089504-4187dab4-1017-11e8-88df-f329943cf13f.png)

gulpfile.js文件
![image](https://user-images.githubusercontent.com/28992657/36089531-5de5822e-1017-11e8-8276-fa2b84e0ce0c.png)

命令行运行gulp script 报下面的错误
![image](https://user-images.githubusercontent.com/28992657/36089386-99b3dd10-1016-11e8-82b0-1505a12573e3.png)
求解！！！

**Comment by LiuwqGit** [comment]
看报错的内容，第8行多了一个分号，我有理由相信，你实际运行的gulpfile.js文件与你的截图文件不同。我猜测，你的第7行代码`.gulp.src('');`估计也写了分号。

**Comment by LiuwqGit** [comment]
@ZhaoYLi 看报错的内容，第8行多了一个分号，我有理由相信，你实际运行的gulpfile.js文件与你的截图文件不同。我猜测，你的第7行代码.gulp.src('');估计也写了分号。

**Comment by LiuwqGit** [comment]
@ZhaoYLi 看报错的内容，第8行多了一个分号，我有理由相信，你实际运行的gulpfile.js文件与你的截图文件不同。我猜测，你的第6行代码.gulp.src('');估计也写了分号。
